[package]
name = "example-segments"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
crunchio = { path = "../../crunchio" }
reqwest = { version = "0.11", features = ["blocking"] }
thiserror = "1"
http = "0.2"
url = "*"
