[package]
name = "example-axdev"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.6.20"

[dev-dependencies]
anyhow = "1"
httpc-test = "0.1"
