[package]
name = "routers"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
uuid = { version = "1.4.1", features = ["serde", "v4"] }
thiserror = "1"
url = "1"

[lib]
name = "routers"
path = "src/lib.rs"
